### PR TITLE
Merge pull request #2 from MicrosoftDocs/main

### PR DESCRIPTION
**Pull request by ExSan**
First Pull Request 2

### CODE REVIEW

**Comment by ExSan** [comment]
ok

**Comment by ExSan** [comment]
olk

**Comment by ExSan** [comment]
sync all

**Comment by ExSan** [comment]
it is  fine

**Comment by ExSan** [comment]
ok

**Comment by ExSan** [comment]
fine

**Comment by stevewhims** [comment]
Not seeing any changes here. Closing. Thanks!

**Pull request closed without merging**
